# Generated by Django 2.0.3 on 2018-03-24 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ttrackerapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'issue_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'issue_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IssueIssue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
                ('is_solved', models.BooleanField()),
                ('solved', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='category', default=ttrackerapp.models.IssueIssue.defaultcategory, on_delete=django.db.models.deletion.PROTECT, to='ttrackerapp.IssueCategory')),
                ('owner', models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owners', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(db_column='reporter', default=ttrackerapp.models.IssueIssue.defaultreporter, on_delete=django.db.models.deletion.PROTECT, related_name='reporters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issue_issue',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='issueissue',
            name='status',
            field=models.ForeignKey(db_column='status', default=ttrackerapp.models.IssueIssue.defaultstatus, on_delete=django.db.models.deletion.PROTECT, to='ttrackerapp.IssueStatus'),
        ),
    ]
