# Generated by Django 2.0.3 on 2018-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecategory',
            options={'managed': True, 'verbose_name': 'Issue Category', 'verbose_name_plural': 'Issue Categories'},
        ),
        migrations.AlterModelOptions(
            name='issueissue',
            options={'managed': True, 'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'managed': True, 'verbose_name': 'Issue Status', 'verbose_name_plural': 'Issue Statuses'},
        ),
        migrations.AlterField(
            model_name='issueissue',
            name='created',
            field=models.DateTimeField(verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='issueissue',
            name='is_solved',
            field=models.BooleanField(verbose_name='Solved'),
        ),
        migrations.AlterField(
            model_name='issueissue',
            name='solved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date solved'),
        ),
    ]
